export type Product = {
  id: string;
  sku: string;
  name: string;
  shortDesc: string;
  fullDesc: string;
  price: number;
  category: "WordPress Themes" | "Shopify Themes" | "Plugins" | "UI Kits" | "Website Templates" | "Extensions";
  image: string;
};

export const products: Product[] = [
  {
    id: "1",
    sku: "SH-WT-001",
    name: "Aurora Business WordPress Theme",
    shortDesc: "Modern, conversion-focused theme for agencies and consultancies.",
    fullDesc: "Aurora is a fully responsive WordPress theme built for agencies, consultancies, and professional services. It ships with the Elementor page builder, six pre-built homepage layouts, a built-in booking widget, and a dark-mode toggle. Optimised for Core Web Vitals, translation-ready, and backed by lifetime updates and 6 months of priority support.",
    price: 59.00,
    category: "WordPress Themes",
    image: "/products/aurora-business-theme.png",
  },
  {
    id: "2",
    sku: "SH-ST-001",
    name: "Nova Shopify Theme",
    shortDesc: "High-conversion Shopify theme for modern DTC brands.",
    fullDesc: "Nova is a lightweight, blazing-fast Shopify OS 2.0 theme designed for direct-to-consumer brands. Includes sticky add-to-cart, mega menu, quick-view modals, bundle and upsell sections, and full support for Shopify Markets. Every section is fully customisable in the theme editor — no coding required.",
    price: 69.00,
    category: "Shopify Themes",
    image: "/products/nova-shopify-theme.png",
  },
  {
    id: "3",
    sku: "SH-PL-001",
    name: "SEO Booster Pro",
    shortDesc: "All-in-one on-page SEO plugin for WordPress.",
    fullDesc: "SEO Booster Pro analyses every page and post in real time, generating schema markup, XML sitemaps, and Open Graph tags automatically. Includes a keyword density checker, broken-link scanner, and a content-score engine that suggests improvements as you write. Compatible with all major page builders.",
    price: 29.00,
    category: "Plugins",
    image: "/products/seo-booster-pro.png",
  },
  {
    id: "4",
    sku: "SH-PL-002",
    name: "Cart Recovery Suite",
    shortDesc: "Automated abandoned-cart recovery for online stores.",
    fullDesc: "Cart Recovery Suite automatically detects abandoned checkouts and triggers a configurable sequence of recovery emails and SMS messages with dynamic discount codes. Includes a real-time analytics dashboard showing recovered revenue, conversion rate, and campaign performance across every channel.",
    price: 35.00,
    category: "Plugins",
    image: "/products/cart-recovery-suite.png",
  },
  {
    id: "5",
    sku: "SH-PL-003",
    name: "Form Builder Pro",
    shortDesc: "Drag-and-drop form builder with conditional logic.",
    fullDesc: "Build multi-step forms, quizzes, and surveys with a true drag-and-drop editor. Form Builder Pro supports conditional logic, file uploads, payment collection via Stripe, and native integrations with 40+ CRM and email marketing tools. Fully accessible and GDPR-compliant out of the box.",
    price: 25.00,
    category: "Plugins",
    image: "/products/form-builder-pro.png",
  },
  {
    id: "6",
    sku: "SH-PL-004",
    name: "Membership & Paywall Plugin",
    shortDesc: "Gated content, subscriptions, and drip-fed courses.",
    fullDesc: "Turn any site into a subscription business. This plugin handles recurring billing, tiered membership levels, drip-fed content schedules, and a fully brandable member dashboard. Integrates directly with Stripe and PayPal, with built-in protection against content scraping and account sharing.",
    price: 89.00,
    category: "Plugins",
    image: "/products/membership-paywall.png",
  },
  {
    id: "7",
    sku: "SH-PL-005",
    name: "Speed Optimizer",
    shortDesc: "One-click performance and caching plugin.",
    fullDesc: "Speed Optimizer combines full-page caching, image lazy-loading, automatic WebP conversion, and critical CSS generation into a single one-click plugin. Most sites see Core Web Vitals scores improve within minutes of activation, with zero manual configuration required.",
    price: 32.00,
    category: "Plugins",
    image: "/products/speed-optimizer.png",
  },
  {
    id: "8",
    sku: "SH-UI-001",
    name: "Dash UI Kit for Figma",
    shortDesc: "400+ component Figma UI kit for SaaS dashboards.",
    fullDesc: "A comprehensive Figma UI kit built for SaaS product teams. Includes over 400 auto-layout components, light and dark variants, a full design-token system, and ready-made dashboard, settings, and onboarding flow templates. Fully compatible with Figma variables for instant theming.",
    price: 79.00,
    category: "UI Kits",
    image: "/products/dash-ui-kit-figma.png",
  },
  {
    id: "9",
    sku: "SH-UI-002",
    name: "Admin Dashboard UI Kit (React)",
    shortDesc: "Production-ready React + Tailwind admin dashboard kit.",
    fullDesc: "A fully coded admin dashboard UI kit built with React, TypeScript, and Tailwind CSS. Includes 60+ components, charts, tables with sorting and pagination, authentication screens, and dark mode. Drop it straight into any Next.js or Vite project and ship your internal tools in hours, not weeks.",
    price: 99.00,
    category: "UI Kits",
    image: "/products/admin-dashboard-ui-kit.png",
  },
  {
    id: "10",
    sku: "SH-WEB-001",
    name: "Portfolio One-Page Template",
    shortDesc: "Minimalist one-page HTML template for creatives.",
    fullDesc: "A clean, minimalist one-page HTML/CSS template built for designers, photographers, and freelancers. Features a smooth-scrolling case-study layout, filterable project grid, and a built-in contact form. No build tools required — just edit and upload.",
    price: 39.00,
    category: "Website Templates",
    image: "/products/portfolio-one-page.png",
  },
  {
    id: "11",
    sku: "SH-WT-002",
    name: "Blog Magazine WordPress Theme",
    shortDesc: "Editorial-grade theme for publishers and bloggers.",
    fullDesc: "Blog Magazine is built for high-traffic publishers. It includes custom homepage layouts for breaking news, featured stories, and category hubs, native ad-slot placements, AMP support, and a reading-progress bar. Ships with a companion newsletter sign-up block for growing your audience.",
    price: 49.00,
    category: "WordPress Themes",
    image: "/products/blog-magazine-theme.png",
  },
  {
    id: "12",
    sku: "SH-EXT-001",
    name: "Analytics Widget Extension",
    shortDesc: "Embeddable real-time analytics dashboard widget.",
    fullDesc: "A lightweight, embeddable JavaScript widget that renders a live analytics dashboard directly on your site or internal tool. Supports custom metrics, goal tracking, and white-labelling, with a single-line install snippet compatible with any framework or CMS.",
    price: 45.00,
    category: "Extensions",
    image: "/products/analytics-widget-extension.png",
  },
];
